#line 1 "cool-lex.cc"

#line 3 "cool-lex.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */
/* %if-c-only */
/* %if-not-reentrant */

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */

/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* begin standard C++ headers. */
/* %if-c++-only */
/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */
/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */
/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */
/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

/* %endif */

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define FLEX_DEBUG
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[316] =
    {   0,
        0,    0,    6,    6,    0,    0,   55,   53,    2,    1,
        9,   24,   25,   17,   15,   16,   28,   18,   50,   29,
       30,   21,   19,   13,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   26,   27,   14,    6,
       24,    6,   17,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,   12,   11,
       24,   17,   16,   10,    2,    4,    5,    3,   20,   22,

       23,   51,   51,   51,   51,   51,   35,   32,   36,   51,
       51,   51,   51,   51,   46,   51,   51,   51,   52,   52,
       52,   52,   52,   52,   35,   32,   36,   52,   52,   52,
       52,   52,   46,   52,   52,   52,   52,    6,    7,    8,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    3,
       51,   51,   51,   51,   51,   51,   39,   51,   45,   47,
       51,   51,   51,   52,   52,   52,   52,   52,   52,   52,

       39,   52,   45,   47,   52,   52,   52,   52,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,   43,   51,   34,   44,
       51,   51,   40,   41,   33,   51,   43,   52,   34,   44,
       52,   52,   52,   40,   41,   33,   48,   52,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
       31,   51,   51,   42,   31,   49,   52,   52,   42,    6,
        6,    6,    6,    6,    6,    6,    6,    6,   51,   38,

       52,   38,    6,    6,    6,    6,   51,   52,    6,    6,
       37,   37,    6,    6,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    5,
        6,    7,    8,    1,    9,   10,   11,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,   14,   15,
       16,   17,    1,   18,   19,   20,   21,   22,   23,   24,
       20,   25,   26,   20,   20,   27,   20,   28,   29,   30,
       20,   31,   32,   33,   34,   35,   36,   20,   20,   20,
        1,    1,    1,    1,   37,    1,   38,   39,   40,   41,

       42,   43,   39,   44,   45,   39,   39,   46,   39,   47,
       48,   49,   39,   50,   51,   52,   53,   54,   55,   39,
       39,   39,   56,    1,   57,   58,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[60] =
    {   0,
        1,    1,    2,    1,    3,    1,    3,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[324] =
    {   0,
        0,    0,   59,    0,  117,  125,  223, 1188,  217, 1188,
     1188,  210, 1188,  210, 1188,  206, 1188, 1188, 1188, 1188,
     1188,  122,  196, 1188,    0,  106,  108,   97,  113,  120,
      124,  112,  110,  121,  123,    0,  142,  143,  152,  149,
      156,  164,  139,  154,  170,  161, 1188, 1188, 1188,    0,
      204,    0,  203,    0,    0,    0,    0,    0,    0,    0,
      141,  190,    0,  220,  279,  213,  220,  320,  225,  280,
      281,  283,  315,  324,  371,  430,  223,  364,  471,  374,
      377,  431,  432,  435,  380,    0,    0,    0, 1188, 1188,
     1188, 1188, 1188, 1188,  201, 1188, 1188,    0, 1188, 1188,

     1188,    0,  159,  180,  176,  222,    0,    0,  218,  214,
      220,  227,  246,  271,    0,  282,  290,  288,    0,  309,
      326,  314,  331,  328,    0,    0,  332,  357,  361,  366,
      362,  400,    0,  408,  430,  429,  438,    0, 1188, 1188,
        0,    0,    0,  473,  474,  475,  478,  477,  507,  508,
      511,  512,  529,  513,  533,  545,  546,  558,  563,  576,
      580,  581,  593,  596,  597,  598,  610,  611,  626,  627,
      633,  640,  655,  656,  649,  671,  680,  677,  686,    0,
      442,  512,  547,  553,  635,  632,    0,  667,    0,    0,
      679,  686,  693,  698,  695,  705,  708,  702,  712,  707,

        0,  707,    0,    0,  711,  713,  719,  716,  740,  739,
      745,  754,  757,  769,  770,  774,  783,  786,  787,  799,
      792,  812,  809,  821,  830,  834,  846,  852,  837,  859,
      855,  868,  872,  875,  888,  885,    0,  718,    0,    0,
      720,  817,    0,    0,    0,  854,    0,  877,    0,    0,
      893,  886,  893,    0,    0,    0,    0,  897,  905,  910,
      906,  922,  926,  928,  931,  940,  943,  952,  961,  964,
      965,  966,  978,  987, 1000,  990,  994, 1003, 1004, 1016,
        0,  901,  941,    0,    0,    0, 1003, 1012,    0, 1025,
     1038, 1047, 1032, 1041, 1048, 1054, 1076, 1063, 1039,    0,

     1044,    0, 1078, 1083, 1085, 1088, 1057, 1074, 1100, 1101,
        0,    0, 1116, 1117, 1188,  170,  147, 1163, 1167, 1171,
     1175, 1179, 1183
    } ;

static const flex_int16_t yy_def[324] =
    {   0,
      315,    1,  315,    3,    1,    1,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  315,  315,  315,  318,
      319,  318,  320,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  321,  321,   65,   65,   65,   65,   65,
       65,   65,   65,   65,  322,  322,   76,   76,   76,   76,
       76,   76,   76,   76,   76,  318,  318,  318,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  323,  315,  315,

      315,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  318,  315,  315,
      318,  318,  318,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,  323,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  317,  317,  317,  317,  317,  317,  317,

      317,  317,  317,  317,  317,  317,  317,  317,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
      316,  316,  316,  316,  317,  317,  317,  317,  317,   65,
       65,   65,   65,   76,   76,   76,   76,   76,  316,  316,

      317,  317,   65,   65,   76,   76,  316,  317,   65,   76,
      316,  317,   65,   76,    0,  315,  315,  315,  315,  315,
      315,  315,  315
    } ;

static const flex_int16_t yy_nxt[1248] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,    8,   24,   25,   25,
       26,   25,   27,   28,   25,   29,   30,   31,   32,   33,
       25,   25,   34,   25,   25,   35,    8,   36,   36,   37,
       36,   38,   39,   36,   40,   41,   42,   43,   44,   36,
       36,   45,   36,   36,   46,   47,   48,   49,    8,   50,
       50,   10,   50,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,   50,   63,   64,   64,   65,
       64,   66,   67,   64,   68,   69,   70,   71,   72,   64,
       64,   73,   64,   64,   74,   50,   75,   75,   76,   75,

       77,   78,   75,   79,   80,   81,   82,   83,   75,   75,
       84,   75,   75,   85,   86,   87,   88,   50,    8,   89,
       90,   91,  107,   92,  103,   93,    8,   89,   90,   91,
       99,   92,  104,   93,  105,  115,  108,  100,  116,  106,
      109,  107,  111,  103,  110,  117,  113,  118,  112,  141,
      119,  104,  114,  105,  115,  108,  142,  116,  106,  109,
      120,  111,  133,  110,  117,  113,  118,  112,  121,  122,
      124,  114,  126,  102,  123,   94,  127,  125,  129,  120,
      128,  133,  134,   94,  130,  137,  131,  121,  122,  124,
      181,  126,  132,  123,  135,  127,  125,  129,  182,  128,

      136,  134,   95,  130,  137,  131,  143,  183,   97,  181,
       96,  132,  101,  135,   98,   97,   96,  182,   95,  136,
      138,  138,  315,  138,  315,  138,  183,  138,  138,  138,
      138,  144,  138,  138,  138,  138,  138,  138,  144,  147,
      184,  161,  185,  144,  148,  149,  144,  153,  186,  164,
      144,  144,  187,  154,  165,  188,  315,  144,  147,  184,
      161,  185,  144,  148,  149,  144,  153,  186,  164,  315,
      144,  187,  154,  165,  188,  138,  138,  138,  138,  138,
      138,  189,  138,  315,  138,  315,  138,  138,  138,  138,
      315,  138,  138,  138,  138,  138,  138,  145,  144,  144,

      189,  144,  155,  190,  157,  146,  144,  144,  156,  144,
      191,  158,  192,  193,  315,  315,  145,  144,  144,  315,
      144,  155,  190,  157,  146,  144,  144,  156,  144,  191,
      158,  192,  193,  144,  138,  138,  138,  138,  144,  159,
      194,  144,  144,  150,  195,  196,  144,  151,  160,  197,
      144,  152,  144,  315,  198,  315,  199,  144,  159,  194,
      144,  144,  150,  195,  196,  144,  151,  160,  197,  144,
      152,  138,  138,  198,  138,  199,  138,  315,  138,  138,
      138,  138,  166,  138,  138,  138,  138,  138,  138,  167,
      161,  200,  161,  201,  202,  161,  171,  203,  161,  173,

      161,  166,  172,  161,  179,  174,  161,  315,  167,  161,
      200,  161,  201,  202,  161,  171,  203,  161,  173,  161,
      315,  172,  161,  179,  174,  161,  138,  138,  138,  138,
      138,  138,  204,  138,  315,  138,  205,  138,  138,  138,
      138,  315,  138,  138,  138,  138,  138,  138,  162,  161,
      161,  204,  206,  161,  175,  205,  163,  161,  161,  177,
      176,  161,  207,  208,  237,  178,  315,  162,  161,  161,
      315,  206,  161,  175,  315,  163,  161,  161,  177,  176,
      161,  207,  208,  237,  178,  138,  138,  138,  138,  161,
      315,  144,  144,  210,  168,  212,  144,  161,  169,  144,

      144,  144,  170,  144,  144,  209,  315,  315,  161,  211,
      144,  144,  210,  168,  212,  144,  161,  169,  144,  144,
      144,  170,  144,  144,  209,  144,  144,  315,  211,  144,
      144,  144,  315,  144,  144,  213,  315,  144,  144,  144,
      315,  216,  315,  238,  144,  144,  214,  144,  144,  144,
      144,  144,  144,  144,  213,  144,  144,  144,  144,  144,
      216,  215,  238,  144,  144,  214,  144,  315,  217,  239,
      144,  144,  144,  240,  144,  315,  144,  218,  144,  315,
      215,  144,  144,  144,  144,  220,  219,  217,  239,  144,
      144,  144,  240,  315,  144,  144,  218,  315,  161,  161,

      144,  221,  144,  144,  220,  219,  161,  161,  144,  315,
      315,  223,  222,  144,  161,  225,  161,  161,  161,  161,
      221,  144,  161,  161,  226,  161,  161,  224,  161,  161,
      223,  222,  315,  161,  225,  161,  161,  161,  161,  315,
      315,  161,  161,  226,  161,  161,  224,  161,  161,  315,
      227,  161,  161,  161,  315,  161,  161,  241,  161,  161,
      242,  228,  315,  161,  161,  229,  161,  161,  230,  227,
      161,  161,  161,  161,  161,  161,  241,  161,  161,  242,
      228,  161,  161,  315,  229,  161,  161,  230,  232,  161,
      231,  315,  161,  161,  161,  161,  243,  161,  161,  233,

      161,  161,  234,  161,  161,  244,  161,  232,  161,  231,
      235,  236,  161,  245,  161,  243,  161,  161,  233,  246,
      247,  234,  161,  161,  244,  161,  248,  249,  250,  235,
      236,  161,  245,  251,  252,  253,  254,  255,  246,  247,
      256,  257,  258,  315,  315,  248,  249,  250,  315,  281,
      282,  315,  251,  252,  253,  254,  255,  144,  144,  256,
      257,  258,  259,  144,  315,  144,  144,  261,  281,  282,
      260,  144,  144,  315,  262,  144,  144,  144,  315,  263,
      144,  259,  144,  144,  144,  144,  261,  144,  144,  260,
      144,  144,  144,  262,  144,  144,  144,  264,  263,  144,

      144,  144,  144,  265,  144,  144,  144,  144,  315,  144,
      144,  144,  144,  266,  144,  144,  264,  144,  268,  144,
      144,  315,  265,  144,  144,  144,  267,  161,  144,  144,
      161,  144,  266,  315,  269,  161,  144,  268,  161,  161,
      270,  315,  283,  271,  144,  267,  161,  161,  161,  161,
      272,  315,  161,  269,  161,  161,  161,  161,  161,  270,
      161,  283,  271,  161,  161,  273,  161,  161,  274,  272,
      161,  161,  161,  161,  161,  161,  284,  161,  161,  161,
      275,  161,  161,  161,  273,  161,  161,  274,  276,  161,
      161,  161,  161,  161,  161,  284,  161,  161,  277,  275,

      161,  161,  278,  161,  161,  161,  161,  276,  285,  161,
      279,  280,  161,  161,  161,  286,  287,  277,  288,  289,
      161,  278,  161,  144,  144,  161,  299,  285,  144,  279,
      280,  144,  144,  161,  286,  287,  144,  288,  289,  315,
      144,  290,  144,  144,  144,  299,  144,  144,  144,  144,
      144,  144,  144,  292,  144,  144,  291,  144,  144,  144,
      290,  144,  300,  144,  315,  144,  144,  144,  144,  144,
      144,  144,  292,  144,  293,  291,  144,  144,  144,  161,
      144,  300,  161,  161,  161,  144,  315,  161,  144,  144,
      161,  161,  161,  293,  315,  294,  161,  144,  161,  315,

      295,  161,  161,  161,  161,  161,  161,  315,  161,  161,
      161,  161,  161,  161,  294,  161,  161,  296,  161,  295,
      161,  161,  161,  161,  161,  297,  161,  161,  301,  161,
      161,  161,  161,  302,  161,  161,  296,  161,  298,  161,
      161,  161,  161,  144,  297,  161,  315,  301,  161,  161,
      144,  144,  302,  161,  315,  315,  144,  298,  144,  161,
      315,  161,  144,  303,  144,  144,  161,  161,  304,  144,
      144,  307,  161,  144,  161,  144,  308,  144,  161,  305,
      161,  161,  303,  144,  144,  161,  161,  304,  311,  161,
      307,  161,  144,  161,  161,  308,  144,  306,  305,  161,

      161,  144,  161,  161,  144,  312,  161,  311,  161,  144,
      309,  161,  315,  161,  161,  144,  306,  310,  144,  161,
      144,  161,  161,  144,  312,  161,  144,  161,  144,  309,
      161,  313,  314,  161,  144,  161,  310,  144,  161,  315,
      315,  315,  144,  161,  315,  144,  161,  315,  315,  315,
      313,  314,  315,  144,  161,  315,  315,  315,  315,  315,
      315,  144,  161,  138,  315,  315,  138,  139,  139,  139,
      139,  140,  140,  140,  140,  144,  315,  315,  144,  161,
      315,  315,  161,  180,  315,  180,  180,    7,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315
    } ;

static const flex_int16_t yy_chk[1248] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    5,    5,
        5,    5,   28,    5,   26,    5,    6,    6,    6,    6,
       22,    6,   26,    6,   27,   32,   29,   22,   33,   27,
       29,   28,   30,   26,   29,   34,   31,   35,   30,   61,
      317,   26,   31,   27,   32,   29,   61,   33,   27,   29,
       37,   30,   43,   29,   34,   31,   35,   30,   37,   38,
       39,   31,   40,  316,   38,    5,   40,   39,   41,   37,
       40,   43,   44,    6,   41,   46,   42,   37,   38,   39,
      103,   40,   42,   38,   45,   40,   39,   41,  104,   40,

       45,   44,   95,   41,   46,   42,   62,  105,   53,  103,
       51,   42,   23,   45,   16,   14,   12,  104,    9,   45,
       64,   64,    7,   64,    0,   64,  105,   64,   64,   64,
       64,   66,   64,   64,   64,   64,   64,   64,   67,   66,
      106,   77,  109,   69,   66,   67,   67,   69,  110,   77,
       66,   69,  111,   69,   77,  112,    0,   67,   66,  106,
       77,  109,   69,   66,   67,   67,   69,  110,   77,    0,
       69,  111,   69,   77,  112,   64,   64,   64,   64,   65,
       65,  113,   65,    0,   65,    0,   65,   65,   65,   65,
        0,   65,   65,   65,   65,   65,   65,   65,   70,   71,

      113,   72,   70,  114,   71,   65,   70,   71,   70,   72,
      116,   72,  117,  118,    0,    0,   65,   70,   71,    0,
       72,   70,  114,   71,   65,   70,   71,   70,   72,  116,
       72,  117,  118,   73,   65,   65,   65,   65,   68,   73,
      120,   73,   74,   68,  121,  122,   68,   68,   74,  123,
       74,   68,   73,    0,  124,    0,  127,   68,   73,  120,
       73,   74,   68,  121,  122,   68,   68,   74,  123,   74,
       68,   75,   75,  124,   75,  127,   75,    0,   75,   75,
       75,   75,   78,   75,   75,   75,   75,   75,   75,   78,
       78,  128,   80,  129,  130,   81,   80,  131,   85,   81,

       80,   78,   80,   81,   85,   81,   85,    0,   78,   78,
      128,   80,  129,  130,   81,   80,  131,   85,   81,   80,
        0,   80,   81,   85,   81,   85,   75,   75,   75,   75,
       76,   76,  132,   76,    0,   76,  134,   76,   76,   76,
       76,    0,   76,   76,   76,   76,   76,   76,   76,   82,
       83,  132,  135,   84,   82,  134,   76,   82,   83,   84,
       83,   84,  136,  137,  181,   84,    0,   76,   82,   83,
        0,  135,   84,   82,    0,   76,   82,   83,   84,   83,
       84,  136,  137,  181,   84,   76,   76,   76,   76,   79,
        0,  144,  145,  146,   79,  148,  147,   79,   79,  144,

      145,  146,   79,  148,  147,  145,    0,    0,   79,  147,
      144,  145,  146,   79,  148,  147,   79,   79,  144,  145,
      146,   79,  148,  147,  145,  149,  150,    0,  147,  151,
      152,  154,    0,  149,  150,  151,    0,  151,  152,  154,
        0,  154,    0,  182,  149,  150,  152,  153,  151,  152,
      154,  155,  149,  150,  151,  153,  151,  152,  154,  155,
      154,  153,  182,  156,  157,  152,  153,    0,  155,  183,
      155,  156,  157,  184,  153,    0,  158,  156,  155,    0,
      153,  159,  156,  157,  158,  159,  158,  155,  183,  159,
      156,  157,  184,    0,  160,  158,  156,    0,  161,  162,

      159,  160,  160,  158,  159,  158,  161,  162,  159,    0,
        0,  163,  162,  160,  164,  165,  166,  161,  162,  163,
      160,  160,  164,  165,  166,  161,  162,  164,  167,  168,
      163,  162,    0,  164,  165,  166,  167,  168,  163,    0,
        0,  164,  165,  166,  169,  170,  164,  167,  168,    0,
      169,  171,  169,  170,    0,  167,  168,  185,  172,  171,
      186,  170,    0,  169,  170,  171,  172,  175,  172,  169,
      171,  169,  170,  173,  174,  175,  185,  172,  171,  186,
      170,  173,  174,    0,  171,  172,  175,  172,  174,  176,
      173,    0,  173,  174,  175,  178,  188,  176,  177,  176,

      173,  174,  177,  178,  179,  191,  177,  174,  176,  173,
      178,  179,  179,  192,  178,  188,  176,  177,  176,  193,
      194,  177,  178,  179,  191,  177,  195,  196,  197,  178,
      179,  179,  192,  198,  199,  200,  202,  205,  193,  194,
      206,  207,  208,    0,    0,  195,  196,  197,    0,  238,
      241,    0,  198,  199,  200,  202,  205,  210,  209,  206,
      207,  208,  209,  211,    0,  210,  209,  211,  238,  241,
      210,  211,  212,    0,  212,  213,  210,  209,    0,  213,
      212,  209,  211,  213,  210,  209,  211,  214,  215,  210,
      211,  212,  216,  212,  213,  214,  215,  214,  213,  212,

      216,  217,  213,  216,  218,  219,  214,  215,    0,  217,
      221,  216,  218,  219,  214,  215,  214,  220,  221,  216,
      217,    0,  216,  218,  219,  220,  220,  223,  217,  221,
      222,  218,  219,    0,  222,  223,  220,  221,  222,  224,
      223,    0,  242,  224,  220,  220,  223,  224,  225,  222,
      225,    0,  226,  222,  223,  229,  225,  222,  224,  223,
      226,  242,  224,  229,  227,  226,  224,  225,  227,  225,
      228,  226,  227,  231,  229,  225,  246,  230,  228,  226,
      228,  231,  229,  227,  226,  230,  232,  227,  230,  228,
      233,  227,  231,  234,  232,  246,  230,  228,  233,  228,

      231,  234,  234,  236,  230,  232,  235,  230,  248,  233,
      235,  236,  234,  232,  235,  251,  252,  233,  253,  258,
      234,  234,  236,  259,  261,  235,  282,  248,  260,  235,
      236,  259,  261,  235,  251,  252,  260,  253,  258,    0,
      262,  260,  259,  261,  263,  282,  264,  260,  262,  265,
      259,  261,  263,  264,  264,  260,  263,  265,  266,  262,
      260,  267,  283,  263,    0,  264,  266,  262,  265,  267,
      268,  263,  264,  264,  268,  263,  265,  266,  268,  269,
      267,  283,  270,  271,  272,  266,    0,  269,  267,  268,
      270,  271,  272,  268,    0,  270,  273,  268,  269,    0,

      273,  270,  271,  272,  273,  274,  269,    0,  276,  270,
      271,  272,  277,  274,  270,  273,  276,  274,  275,  273,
      277,  278,  279,  273,  274,  275,  275,  276,  287,  278,
      279,  277,  274,  288,  280,  276,  274,  275,  280,  277,
      278,  279,  280,  290,  275,  275,    0,  287,  278,  279,
      293,  290,  288,  280,    0,    0,  291,  280,  293,  294,
        0,  280,  290,  291,  291,  292,  295,  294,  292,  293,
      290,  299,  296,  292,  295,  291,  301,  293,  294,  296,
      296,  298,  291,  291,  292,  295,  294,  292,  307,  298,
      299,  296,  292,  295,  297,  301,  303,  297,  296,  296,

      298,  304,  297,  305,  303,  308,  306,  307,  298,  304,
      303,  305,    0,  297,  306,  303,  297,  305,  309,  310,
      304,  297,  305,  303,  308,  306,  309,  310,  304,  303,
      305,  309,  310,  306,  313,  314,  305,  309,  310,    0,
        0,    0,  313,  314,    0,  309,  310,    0,    0,    0,
      309,  310,    0,  313,  314,    0,    0,    0,    0,    0,
        0,  313,  314,  318,    0,    0,  318,  319,  319,  319,
      319,  320,  320,  320,  320,  321,    0,    0,  321,  322,
        0,    0,  322,  323,    0,  323,  323,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static const flex_int16_t yy_rule_linenum[54] =
    {   0,
       93,   97,   99,  101,  106,  118,  120,  122,  130,  137,
      141,  159,  172,  173,  174,  175,  176,  177,  179,  180,
      181,  182,  183,  185,  186,  187,  188,  189,  190,  191,
      193,  194,  195,  196,  197,  198,  199,  200,  201,  202,
      203,  204,  205,  206,  207,  208,  209,  211,  212,  214,
      216,  217,  219
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cool.flex"
/*
 *  The scanner definition for COOL.
 */
/*
 *  Stuff enclosed in %{ %} in the first section is copied verbatim to the
 *  output, so headers and global definitions are placed here to be visible
 * to the code in the file.  Don't remove anything that was here initially
 */
#line 11 "cool.flex"
#include <cool-parse.h>
#include <stringtab.h>
#include <utilities.h>

/* The compiler assumes these identifiers. */
#define yylval cool_yylval
#define yylex  cool_yylex

/* Max size of string constants */
#define MAX_STR_CONST 1025
#define YY_NO_UNPUT   /* keep g++ happy */
/*
   The two statements below are here just so this program will compile.
   You may need to change or remove them on your final code.
*/
#define yywrap() 1
#define YY_SKIP_YYWRAP

extern FILE *fin; /* we read from this file */

/* define YY_INPUT so we read from the FILE fin:
 * This change makes it possible to use this scanner in
 * the Cool compiler.
 */
#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = fread( (char*)buf, sizeof(char), max_size, fin)) < 0) \
		YY_FATAL_ERROR( "read() in flex scanner failed");

char string_buf[MAX_STR_CONST]; /* to assemble string constants */
char *string_buf_ptr;

extern int curr_lineno;
extern int verbose_flag;

extern YYSTYPE cool_yylval;

/*
 *  Add Your own definitions here
 */

int commentLevel = 0;
std::string readString = "";
int readStringLength = 0;
int readNullToken = 0;

#line 966 "cool-lex.cc"

#line 968 "cool-lex.cc"

#define INITIAL 0
#define COMMENT 1
#define STRING 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals ( void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

/* %not-for-header */
#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */
/* %ok-for-header */

/* %not-for-header */
/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */
/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
/* %% [7.0] user's declarations go here */
#line 91 "cool.flex"


#line 1253 "cool-lex.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 316 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1188 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 54 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 54 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 55 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 93 "cool.flex"
{
   curr_lineno += 1;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 97 "cool.flex"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 99 "cool.flex"
;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 101 "cool.flex"
{
   commentLevel += 1;
   BEGIN COMMENT;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 106 "cool.flex"
{
   commentLevel -= 1;

   if(commentLevel == 0) {
      BEGIN INITIAL;
   } else if(commentLevel == -1) {
      yylval.error_msg = "Unmatched *)";
      commentLevel = 0;
      return (ERROR);
   }
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 118 "cool.flex"
{}
	YY_BREAK
case 7:
/* rule 7 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 1);
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 120 "cool.flex"
;
	YY_BREAK
case 8:
/* rule 8 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 1);
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 122 "cool.flex"
;
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 124 "cool.flex"
{
   BEGIN INITIAL;
   yylval.error_msg = "EOF in comment";
   return (ERROR);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 130 "cool.flex"
{
   BEGIN STRING;
   readString = "";
   readStringLength = 0;
   readNullToken = 0;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 137 "cool.flex"
{
   readNullToken = 1;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 141 "cool.flex"
{
   BEGIN(INITIAL);

   if(readNullToken == 1) {
      BEGIN(INITIAL);
      yylval.error_msg = "String contains null character";
      return (ERROR);
   }

   if(readStringLength >= MAX_STR_CONST) {
      yylval.error_msg = "String constant too long";
      return (ERROR);
   }

   cool_yylval.symbol = stringtable.add_string((char *) readString.c_str());
   return (STR_CONST);
}
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 159 "cool.flex"
{
   BEGIN(INITIAL);
   curr_lineno += 1;
   yylval.error_msg = "Unterminated string constant";
   return (ERROR);
}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 166 "cool.flex"
{
   BEGIN(INITIAL);
   yylval.error_msg = "EOF in string constant";
   return (ERROR);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 172 "cool.flex"
{ return ('@'); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 173 "cool.flex"
{ return ('~'); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 174 "cool.flex"
{ return ('+'); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 175 "cool.flex"
{ return ('-'); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 176 "cool.flex"
{ return ('*'); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 177 "cool.flex"
{ return ('/'); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 179 "cool.flex"
{ return ('='); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 180 "cool.flex"
{ return (ASSIGN); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 181 "cool.flex"
{ return ('<'); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 182 "cool.flex"
{ return (LE); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 183 "cool.flex"
{ return (DARROW); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 185 "cool.flex"
{ return ('('); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 186 "cool.flex"
{ return (')'); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 187 "cool.flex"
{ return ('{'); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 188 "cool.flex"
{ return ('}'); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 189 "cool.flex"
{ return ('.'); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 190 "cool.flex"
{ return (':'); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 191 "cool.flex"
{ return (';'); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 193 "cool.flex"
{ return (CLASS); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 194 "cool.flex"
{ return (IF); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 195 "cool.flex"
{ return (THEN); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 196 "cool.flex"
{ return (ELSE); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 197 "cool.flex"
{ return (FI); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 198 "cool.flex"
{ return (IN); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 199 "cool.flex"
{ return (INHERITS); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 200 "cool.flex"
{ return (ISVOID); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 201 "cool.flex"
{ return (LET); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 202 "cool.flex"
{ return (LOOP); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 203 "cool.flex"
{ return (POOL); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 204 "cool.flex"
{ return (WHILE); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 205 "cool.flex"
{ return (CASE); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 206 "cool.flex"
{ return (ESAC); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 207 "cool.flex"
{ return (NEW); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 208 "cool.flex"
{ return (OF); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 209 "cool.flex"
{ return (NOT); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 211 "cool.flex"
{ cool_yylval.boolean = 1; return (BOOL_CONST); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 212 "cool.flex"
{ cool_yylval.boolean = 0; return (BOOL_CONST); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 214 "cool.flex"
{ cool_yylval.symbol = inttable.add_string(yytext); return (INT_CONST); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 216 "cool.flex"
{ cool_yylval.symbol = idtable.add_string(yytext); return (TYPEID); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 217 "cool.flex"
{ cool_yylval.symbol = idtable.add_string(yytext); return (OBJECTID); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 219 "cool.flex"
{ yylval.error_msg = yytext; return (ERROR); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 221 "cool.flex"
ECHO;
	YY_BREAK
#line 1674 "cool-lex.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
/* %endif */
/* %if-c++-only */
/* %endif */
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */
    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 59);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 316 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 59;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 316 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 315);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */

    static void yyunput (int c, char * yy_bp )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */

/* %endif */
#endif

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/* %if-c++-only */
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
/* %endif */
/* %if-c++-only */
/* %endif */
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/* %if-c++-only */
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

/* %if-c-only */
	b->yy_input_file = file;
/* %endif */
/* %if-c++-only */
/* %endif */
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 221 "cool.flex"


